# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: news_crawler

on:
  schedule:
    - cron: '0 8 * * *'
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run ls -al
        run: |
          ls -al
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        run: |
          python src/main.py
      - name: Run ls -al
        run: |
          ls -al
